service: myexpressstore 

provider:
 name: aws
 runtime: nodejs10.x 
 memorySize: 512
 timeout: 15
 stage: ${opt:stage, 'dev'}
 region: us-east-2 

functions:
 api:
   handler: lambda.handler
   events:
     - http: ANY {proxy+}
     - http: ANY /
     
plugins:
  - serverless-offline